site_name: Sprytile Docs
site_description: A tile map editor for Blender
site_author: Jeiel Aranal
site_url: http://docs.sprytile.xyz
repo_name: "Sprytile Home"
repo_url: http://itch.sprytile.xyz
copyright: Copyright 2016-2020 Jeiel Aranal
site_dir: ../SprytilePage
theme:
  name: 'material'
  icon:
    logo: material/blender-software
    repo: fontawesome/brands/itch-io

nav:
- Home: index.md
- Quick Start: quick-start.md
- Advanced Features: advanced-features.md
- Keyboard Shortcuts: shortcuts.md
- References:
  - Creating Tilesets: creating-tilesets.md
  - Using Tilesets: using-tilesets.md
  - Sketchfab Export: sketchfab.md
  - Unity Settings: unity-settings.md
# - Topics:
#   - Workflow Concepts: workflow-concepts.md
#   - Paint and Build: paint-mode.md
#   - Tile Grids: tile-grids.md
# - Issues: bugs.md

extra_css:
- 'stylesheets/extra.css'

# Options
extra:
  features:
    tabs: false
  palette:
    primary: indigo
    accent: light blue
  social:
    - icon: fontawesome/solid/globe-asia
      link: https://chemikhazi.itch.io/sprytile
    - icon: fontawesome/brands/github
      link: https://github.com/chemikhazi
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jeielvtx

plugins:
  - search

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.meta
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
